/*
 * WMForm.java
 *
 * Created on February 4, 2007, 1:47 AM
 */

package ui;
import com.l2fprod.gui.plaf.skin.SkinLookAndFeel;
import java.awt.Color;
import java.awt.Cursor;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Vector;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;
import player.SamplingGraphs;
import player.Playback;
import player.Capture;
import ui.dialog.BitCheckDialog;
import ui.dialog.ExtractMarkDialog;
import ui.dialog.InsertMarkDialog;
import ui.dialog.OptionDialog;
import ui.dialog.StatistiqueDialog;
import wavemark.*;
import util.WaveInfo;


/**
 *
 * @author  ady
 */
public class MainForm extends javax.swing.JFrame {
    
    public Capture capture = new Capture();
    public Playback playback = new Playback();
    public Vector streamHolder = new Vector();
    public SamplingGraphs sgSource;
    public SamplingGraphs sgTarget;
    Color hover = new Color(104,121,144);
    
    /** Creates new form WMForm */
    public MainForm() {
        initComponents();
        jPanelGraph1.removeAll();
        jPanelGraph1.add(sgSource = new SamplingGraphs(playback,capture));
        sgSource.setVisible(true);
        jPanelGraph1.validate();
        
        jPanelGraph2.removeAll();
        jPanelGraph2.add(sgTarget = new SamplingGraphs(playback,capture));
        sgTarget.setVisible(true);
        jPanelGraph2.validate();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroupMethod = new javax.swing.ButtonGroup();
        buttonGroupExtMethod = new javax.swing.ButtonGroup();
        buttonGroupExtMsg = new javax.swing.ButtonGroup();
        buttonGroupBERSource = new javax.swing.ButtonGroup();
        buttonGroupBERTarget = new javax.swing.ButtonGroup();
        jPanelMainMenu = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelMenu3 = new javax.swing.JPanel();
        jLabelMenu3 = new javax.swing.JLabel();
        jPanelMenu4 = new javax.swing.JPanel();
        jLabelMenu4 = new javax.swing.JLabel();
        jPanelMenu5 = new javax.swing.JPanel();
        jLabelMenu5 = new javax.swing.JLabel();
        jPanelMenu6 = new javax.swing.JPanel();
        jLabelMenu6 = new javax.swing.JLabel();
        jPanelMenu7 = new javax.swing.JPanel();
        jLabelMenu7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelSideCenter = new javax.swing.JPanel();
        jPanelGraph1 = new javax.swing.JPanel();
        jPanelGraph2 = new javax.swing.JPanel();
        jToolBarPlayer = new javax.swing.JToolBar();
        jButtonStop = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();
        jPanelSideRight1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPlaylist = new javax.swing.JList();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableProperties = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARMS: Audio wateRMarking System");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        jPanelMainMenu.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setDividerSize(3);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu3MouseExited(evt);
            }
        });

        jLabelMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/ins.png")));
        jLabelMenu3.setText("Insert Mark");
        jLabelMenu3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelMenu3.add(jLabelMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2.add(jPanelMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jPanelMenu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu4MouseExited(evt);
            }
        });

        jLabelMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/ext.png")));
        jLabelMenu4.setText("Extract Mark");
        jLabelMenu4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMenu4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelMenu4.add(jLabelMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2.add(jPanelMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, 70));

        jPanelMenu5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu5MouseExited(evt);
            }
        });

        jLabelMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/tes.png")));
        jLabelMenu5.setText("Error Test");
        jLabelMenu5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelMenu5.add(jLabelMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2.add(jPanelMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 80, 70));

        jPanelMenu6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenu6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu6MouseExited(evt);
            }
        });

        jLabelMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/bitcheck.png")));
        jLabelMenu6.setText("Recovery Test");
        jLabelMenu6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMenu6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelMenu6.add(jLabelMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2.add(jPanelMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 80, 70));

        jPanelMenu7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMenu7MouseExited(evt);
            }
        });

        jLabelMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/ady1.jpg")));
        jLabelMenu7.setText("About");
        jLabelMenu7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMenu7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelMenu7.add(jLabelMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jPanel2.add(jPanelMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 80, 90));

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanelSideCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSideCenter.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGraph1.setLayout(new java.awt.BorderLayout());

        jPanelSideCenter.add(jPanelGraph1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 210));

        jPanelGraph2.setLayout(new java.awt.BorderLayout());

        jPanelSideCenter.add(jPanelGraph2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 520, 210));

        jToolBarPlayer.setBorder(null);
        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/stop.png")));
        jButtonStop.setText("Stop");
        jButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jToolBarPlayer.add(jButtonStop);

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/play.png")));
        jButtonPlay.setText("Play");
        jButtonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jToolBarPlayer.add(jButtonPlay);

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/pause.png")));
        jButtonPause.setText("Pause");
        jButtonPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });

        jToolBarPlayer.add(jButtonPause);

        jButtonRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/record.png")));
        jButtonRecord.setText("Record");
        jButtonRecord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRecord.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });

        jToolBarPlayer.add(jButtonRecord);

        jPanelSideCenter.add(jToolBarPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 710, -1));

        jPanelSideRight1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSideRight1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);
        jListPlaylist.setSelectionBackground(new java.awt.Color(104, 121, 144));
        jListPlaylist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPlaylistValueChanged(evt);
            }
        });

        jScrollPane5.setViewportView(jListPlaylist);

        jPanelSideRight1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 190));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(51, 95, 130));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("  Available Stream");
        jPanel9.add(jLabel35, java.awt.BorderLayout.CENTER);

        jPanelSideRight1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 20));

        jScrollPane6.setBorder(null);
        jTableProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Properties", "Value"
            }
        ));
        jTableProperties.setSelectionBackground(new java.awt.Color(104, 121, 144));
        jScrollPane6.setViewportView(jTableProperties);

        jPanelSideRight1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 220));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar2.setBorder(null);
        jButton4.setText("  add  ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToolBar2.add(jButton4);

        jButton5.setText("  sav  ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToolBar2.add(jButton5);

        jButton6.setText("  rem  ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jToolBar2.add(jButton6);

        jPanel11.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 20));

        jPanelSideRight1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 170, 20));

        jPanelSideCenter.add(jPanelSideRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 0, 170, 450));

        jPanel3.add(jPanelSideCenter, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel3);

        jPanelMainMenu.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelMainMenu, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 121, 187));
        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/head3.jpg")));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu6MouseClicked
// TODO add your handling code here:
            BitCheckDialog bcd = new BitCheckDialog(this,false,this.getLocationOnScreen());
            bcd.setVisible(true);
    }//GEN-LAST:event_jPanelMenu6MouseClicked

    private void jPanelMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu5MouseClicked
// TODO add your handling code here:
        if (this.streamHolder.size()>1){
            WaveInfo wi1 = (WaveInfo) this.streamHolder.get(0);
            WaveInfo wi2 = (WaveInfo) this.streamHolder.get(1);
            
            StatistiqueDialog ud = new StatistiqueDialog(this,false,this.getLocationOnScreen(),wi1,wi2);
            ud.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Load 2 audio first!!","Warning",JOptionPane.WARNING_MESSAGE);
        }        

    }//GEN-LAST:event_jPanelMenu5MouseClicked

    private void jPanelMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu4MouseClicked
// TODO add your handling code here:
        if (this.streamHolder.size()>0){
            int idx = this.jListPlaylist.getSelectedIndex();       
            WaveInfo wi = (WaveInfo) this.streamHolder.get(idx);
            ExtractMarkDialog emd = new ExtractMarkDialog(this,false,this,wi);
            emd.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Load audio first!!","Warning",JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_jPanelMenu4MouseClicked

    private void jPanelMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseClicked
// TODO add your handling code here:
        if (this.streamHolder.size()>0){
            int idx = this.jListPlaylist.getSelectedIndex();       
            WaveInfo wi = (WaveInfo) this.streamHolder.get(idx);
            InsertMarkDialog imd = new InsertMarkDialog(this,false,this,wi);
            imd.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Load audio first!!","Warning",JOptionPane.WARNING_MESSAGE);
        }
            
    }//GEN-LAST:event_jPanelMenu3MouseClicked

    private void jPanelMenu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu7MouseExited
// TODO add your handling code here:
        jPanelMenu7.setBackground(Color.white);
        jLabelMenu7.setForeground(Color.black);    
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_jPanelMenu7MouseExited

    private void jPanelMenu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu7MouseEntered
// TODO add your handling code here:
        jPanelMenu7.setBackground(hover);
        jLabelMenu7.setForeground(Color.white);     
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
       
    }//GEN-LAST:event_jPanelMenu7MouseEntered

    private void jPanelMenu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu6MouseExited
// TODO add your handling code here:
        jPanelMenu6.setBackground(Color.white);
        jLabelMenu6.setForeground(Color.black);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        
    }//GEN-LAST:event_jPanelMenu6MouseExited

    private void jPanelMenu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu6MouseEntered
// TODO add your handling code here:
        jPanelMenu6.setBackground(hover);
        jLabelMenu6.setForeground(Color.white);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));       
    }//GEN-LAST:event_jPanelMenu6MouseEntered

    private void jPanelMenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu5MouseExited
// TODO add your handling code here:
        jPanelMenu5.setBackground(Color.white);
        jLabelMenu5.setForeground(Color.black);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));


    }//GEN-LAST:event_jPanelMenu5MouseExited

    private void jPanelMenu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu5MouseEntered
// TODO add your handling code here:
        jPanelMenu5.setBackground(hover);
        jLabelMenu5.setForeground(Color.white);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
       

    }//GEN-LAST:event_jPanelMenu5MouseEntered

    private void jPanelMenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu4MouseExited
// TODO add your handling code here:
        jPanelMenu4.setBackground(Color.white);
        jLabelMenu4.setForeground(Color.black);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));


    }//GEN-LAST:event_jPanelMenu4MouseExited

    private void jPanelMenu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu4MouseEntered
// TODO add your handling code here:
        jPanelMenu4.setBackground(hover);
        jLabelMenu4.setForeground(Color.white);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        

    }//GEN-LAST:event_jPanelMenu4MouseEntered

    private void jPanelMenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseExited
// TODO add your handling code here:
        jPanelMenu3.setBackground(Color.white);
        jLabelMenu3.setForeground(Color.black);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelMenu3MouseExited

    private void jPanelMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenu3MouseEntered
// TODO add your handling code here:
        jPanelMenu3.setBackground(hover);
        jLabelMenu3.setForeground(Color.white);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelMenu3MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.streamHolder.removeAllElements();
        sgSource.clearGraph();
        sgTarget.clearGraph();
        this.setStreamList();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            File file = new File(System.getProperty("user.dir"));
            JFileChooser fc = new JFileChooser(file);
            fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
                public boolean accept(File f) {
                    if (f.isDirectory()) {
                        return true;
                    }
                    String name = f.getName();
                    if (name.endsWith(".wav")) {
                        return true;
                    }
                    return false;
                }
                public String getDescription() {
                    return ".wav";
                }
            });
            
            if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                int idx = this.jListPlaylist.getSelectedIndex();
                WaveInfo waveInfo =  (WaveInfo) this.streamHolder.get(idx);
                waveInfo.saveToFile(fc.getSelectedFile().getAbsoluteFile() + ".wav",AudioFileFormat.Type.WAVE);
            }
        } catch (SecurityException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            //File file = new File( System.getProperty("user.dir"));
            JFileChooser fc = new JFileChooser();
            fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
                public boolean accept(File f) {
                    if (f.isDirectory()) {
                        return true;
                    }
                    String name = f.getName();
                    if (name.endsWith(".wav")) {
                        return true;
                    }
                    return false;
                }
                public String getDescription() {
                    return ".wav";
                }
            });
            
            if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                this.addStreamtoList(0, new WaveInfo(fc.getSelectedFile()));
                this.setStreamList();
                this.sgSource.setSourceStream((WaveInfo) this.streamHolder.get(0));
                this.sgSource.createWaveForm();
            }
        } catch (SecurityException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jListPlaylistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPlaylistValueChanged
        if (this.jListPlaylist.getSelectedIndex() != -1)
            jTableProperties.setModel(this.setTableModel());
    }//GEN-LAST:event_jListPlaylistValueChanged

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
        this.capture.setSamplingGraph(sgSource);
        this.capture.setForm(this);
        this.capture.start();
        this.capture.samplingGraph.start();
    }//GEN-LAST:event_jButtonRecordActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
        if (this.capture.thread != null) {
            capture.line.stop();
        }else if (this.playback.thread != null) {
            this.playback.line.stop();
        }
    }//GEN-LAST:event_jButtonPauseActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (this.capture.thread != null) {
            capture.line.start();
        } else if (this.playback.thread != null) {
            this.playback.line.start();
        }else{
            int idx = this.jListPlaylist.getSelectedIndex();
            this.playback.setSourceStream((WaveInfo) this.streamHolder.get(idx));
            if (idx == 0)
                this.playback.setSamplingGraph(this.sgSource);
            else
                this.playback.setSamplingGraph(this.sgTarget);
            
            this.playback.start();
            this.playback.samplingGraph.start();
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        if (this.capture.thread != null) {
            this.capture.stop();
            this.capture.samplingGraph.stop();
        } else if (this.playback.thread != null) {
            this.playback.stop();
            this.playback.samplingGraph.stop();
        }
    }//GEN-LAST:event_jButtonStopActionPerformed
    
   public void setWaveSource(WaveInfo waveInfo){
       this.streamHolder.add(0, waveInfo);
   }
      
   
   public void setStreamList(){
       jListPlaylist.removeAll();
       jListPlaylist.setListData(this.streamHolder);
       jListPlaylist.setSelectedIndex(this.streamHolder.size()-1);
   }
   
   public void addStreamtoList( int idx, WaveInfo waveInfo){
       this.streamHolder.add(idx,waveInfo);

       if (this.streamHolder.size() > idx+1)    
           this.streamHolder.removeElementAt(idx+1);
  }
   
  public DefaultTableModel setTableModel(){
      Vector colname = new Vector();
      colname.add("Properties");
      colname.add("Values");
      
      WaveInfo waveInfo = (WaveInfo) this.streamHolder.get(this.jListPlaylist.getSelectedIndex());
      Vector info = waveInfo.getProperties();
      DefaultTableModel tableModel = new DefaultTableModel( info, colname);
      
      return tableModel;
  }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try{
          String dir = System.getProperty("user.dir");
          
          SkinLookAndFeel.setSkin(SkinLookAndFeel.loadThemePack(dir + "\\skin\\" + "tiger.zip"));
          UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
          //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            e.printStackTrace();
        }

        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                System.out.println("Wavemark running...");
            }
        });}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroupBERSource;
    private javax.swing.ButtonGroup buttonGroupBERTarget;
    private javax.swing.ButtonGroup buttonGroupExtMethod;
    private javax.swing.ButtonGroup buttonGroupExtMsg;
    private javax.swing.ButtonGroup buttonGroupMethod;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabelMenu3;
    private javax.swing.JLabel jLabelMenu4;
    private javax.swing.JLabel jLabelMenu5;
    private javax.swing.JLabel jLabelMenu6;
    private javax.swing.JLabel jLabelMenu7;
    private javax.swing.JList jListPlaylist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelGraph1;
    private javax.swing.JPanel jPanelGraph2;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelMenu3;
    private javax.swing.JPanel jPanelMenu4;
    private javax.swing.JPanel jPanelMenu5;
    private javax.swing.JPanel jPanelMenu6;
    private javax.swing.JPanel jPanelMenu7;
    private javax.swing.JPanel jPanelSideCenter;
    private javax.swing.JPanel jPanelSideRight1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableProperties;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBarPlayer;
    // End of variables declaration//GEN-END:variables
    
}
