/*
 * BitCheckDialog.java
 *
 * Created on April 23, 2007, 12:19 PM
 */

package ui.dialog;

import java.awt.Color;
import java.awt.Point;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;

/**
 *
 * @author  administrator
 */
public class BitCheckDialog extends javax.swing.JDialog {
    
    /** Creates new form BitCheckDialog */
    public BitCheckDialog(java.awt.Frame parent, boolean modal,Point pos) {
        super(parent, modal);
        initComponents();
        this.setLocation(pos.x + (800 - getWidth()),pos.y + (600 - getHeight()));      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelUtil = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButtonCountStat = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButtonLoad1 = new javax.swing.JButton();
        jButtonLoad2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelBER = new javax.swing.JLabel();
        jLabelRRate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanelUtil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelUtil.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Georgia", 1, 14));
        jLabel35.setText("Check da Error Rate");
        jPanelUtil.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/bitcheck.png")));
        jPanelUtil.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, 40));

        jPanelUtil.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 10));

        jButtonCountStat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/misc.png")));
        jButtonCountStat.setText(" Count");
        jButtonCountStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountStatActionPerformed(evt);
            }
        });

        jPanelUtil.add(jButtonCountStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jPanelUtil.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, -1));

        jLabel1.setText("Select original message");
        jPanelUtil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wavemark/images/corner.jpg")));
        jPanelUtil.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 290, 110, 200));

        jButtonLoad1.setText("...");
        jButtonLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoad1ActionPerformed(evt);
            }
        });

        jPanelUtil.add(jButtonLoad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, -1));

        jButtonLoad2.setText("...");
        jButtonLoad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoad2ActionPerformed(evt);
            }
        });

        jPanelUtil.add(jButtonLoad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 40, -1));

        jPanelUtil.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 300, -1));

        jLabel2.setText("Select Extracted message");
        jPanelUtil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        jPanelUtil.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 340, 160));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Bit Errorr Rate");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Recovery Rate");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText(":");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(":");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelBER.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelBER.setText("   ");
        jPanel2.add(jLabelBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, -1));

        jLabelRRate.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelRRate.setText("   ");
        jPanel2.add(jLabelRRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 140, -1));

        jPanelUtil.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 340, 50));

        jScrollPane2.setViewportView(jTextPane2);

        jPanelUtil.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 160));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelUtil.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 20, 410));

        jLabel7.setText("Just check if you want recovery rate each method.");
        jPanelUtil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        getContentPane().add(jPanelUtil, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-520)/2, 800, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoad2ActionPerformed
        try {
            File file = new File(System.getProperty("user.dir"));
            JFileChooser fc = new JFileChooser(file);
            if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                jTextField2.setText(fc.getSelectedFile().getCanonicalPath());
                FileInputStream fis = new FileInputStream(fc.getSelectedFile());
                BufferedInputStream bis = new BufferedInputStream(fis);
                byte[] datateks = new byte[bis.available()];
                bis.read(datateks);
                String teks = new String(datateks);
                jTextPane1.setText(teks);
                bis.close();
                fis.close();            
            }
        } catch (SecurityException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_jButtonLoad2ActionPerformed

    private void jButtonLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoad1ActionPerformed
// TODO add your handling code here:
        try {
            File file = new File(System.getProperty("user.dir"));
            JFileChooser fc = new JFileChooser(file);
            if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                jTextField1.setText(fc.getSelectedFile().getCanonicalPath());
            
                FileInputStream fis = new FileInputStream(fc.getSelectedFile());
                BufferedInputStream bis = new BufferedInputStream(fis);
                byte[] datateks = new byte[bis.available()];
                bis.read(datateks);
                String teks = new String(datateks);
                jTextPane2.setText(teks);
                bis.close();
                fis.close();
                
            }
        } catch (SecurityException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonLoad1ActionPerformed

    private void jButtonCountStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountStatActionPerformed
      if (!jTextField1.getText().equals("") && !jTextField2.getText().equals("")){        
        double bitError = 0;
        double bitAvailable = 0;
        try {
            
            FileInputStream file1 = new FileInputStream(jTextField1.getText());
            FileInputStream file2 = new FileInputStream(jTextField2.getText());
            
            bitAvailable = file1.available();
            
            int offset = 0;
            while (file1.available() > 0){
                int byte1 = file1.read();
                int byte2 = file2.read();
                
                if (byte1 != byte2){
                    bitError++;                 
                }
                offset++;
            }

            double BER =bitError/bitAvailable * 100;
            
            DecimalFormat df = new DecimalFormat("###.##");
            jLabelBER.setText(df.format(BER) + "%");
            jLabelRRate.setText(df.format(100-BER) + "%");
            //jTextPane1.setSelectedTextColor(Color.RED);
            
            
            
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
      }
        
        
    }//GEN-LAST:event_jButtonCountStatActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCountStat;
    private javax.swing.JButton jButtonLoad1;
    private javax.swing.JButton jButtonLoad2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBER;
    private javax.swing.JLabel jLabelRRate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelUtil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
    
}
